---
name: Continuous Delivery (Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  delivery-nodejs:
    name: Delivery to NPM
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: olegtarasov/get-tag@v2
        id: tag_name
        with:
          tagRegex: 'v(.*)'
      - name: Install Dependencies with NPM
        id: installing
        run: |
          npm ci --no-optional
          npm pack
      - name: Upload Changelog
        id: upload_artifact
        uses: actions/upload-artifact@v1
        with:
          name: changelog
          path: CHANGELOG.md
      - name: Upload NPM Artifacts
        id: upload_npm
        uses: actions/upload-artifact@v1
        with:
          name: package-npm
          path: serverless-typescript-api-${{ steps.tag_name.outputs.tag }}.tgz

  delivery-github:
    name: Delivery to GitHub
    needs: delivery-nodejs
    runs-on: ubuntu-18.04
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tag_name
        with:
          tagRegex: 'v(.*)'
      - name: Download Changelog
        id: download_changelog
        uses: actions/download-artifact@v1
        with:
          name: changelog
          path: CHANGELOG.md
      - name: Download NPM Artifacts
        id: download_npm
        uses: actions/download-artifact@v1
        with:
          name: package-npm
          path: serverless-typescript-api-${{ steps.tag_name.outputs.tag }}.tgz
      - name: GitHub Release
        id: releasing
        uses: docker://antonyurchenko/git-release:v3.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'true'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'false'
          ALLOW_TAG_PREFIX: 'true'
        with:
          args: |
              serverless-typescript-api-${{ steps.tag_name.outputs.tag }}.tgz
